name: Lint Repo
on:
  - pull_request
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
jobs:
  build:
    name: Lint
    runs-on: ${{ vars.WF_UBUNTU_LTS }}
    strategy:
      matrix:
        node-version:
          - "${{ vars.WF_NODEJS_LATEST }}"
          - "${{ vars.WF_NODEJS_OLD }}"
    steps:
      - name: Checkout Release from lens
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Using Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install specific npm version
        run: npm install -g npm@^9.6.7

      - name: Install deps
        run: npm install

      - name: Lint
        run: npm run lint

      - name: Verify Publish Configurations
        run: ./scripts/lint-publish-configs.sh

      - name: Verify No Duplicate Dependencies
        run: ./scripts/lint-package-dependencies.sh
